
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://111.231.57.118:3306/rich?useUnicode=true&characterEncoding=utf8
    username: root
    password: Kuma11290213
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.zhang.model
  mapperLocations: classpath:com/zhang/model/mapper/*.xml